// Protocol subset used by x/v2/dm/web/seg.so.
// Field numbers match bilibili.community.service.dm.v1.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: proto/danmaku.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DmSegMobileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elems         []*DanmakuElem         `protobuf:"bytes,1,rep,name=elems,proto3" json:"elems,omitempty"`
	State         int32                  `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	AiFlag        *DanmakuAIFlag         `protobuf:"bytes,3,opt,name=ai_flag,json=aiFlag,proto3" json:"ai_flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DmSegMobileReply) Reset() {
	*x = DmSegMobileReply{}
	mi := &file_proto_danmaku_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DmSegMobileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DmSegMobileReply) ProtoMessage() {}

func (x *DmSegMobileReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_danmaku_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DmSegMobileReply.ProtoReflect.Descriptor instead.
func (*DmSegMobileReply) Descriptor() ([]byte, []int) {
	return file_proto_danmaku_proto_rawDescGZIP(), []int{0}
}

func (x *DmSegMobileReply) GetElems() []*DanmakuElem {
	if x != nil {
		return x.Elems
	}
	return nil
}

func (x *DmSegMobileReply) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *DmSegMobileReply) GetAiFlag() *DanmakuAIFlag {
	if x != nil {
		return x.AiFlag
	}
	return nil
}

type DanmakuElem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Progress      int32                  `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	Mode          int32                  `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Fontsize      int32                  `protobuf:"varint,4,opt,name=fontsize,proto3" json:"fontsize,omitempty"`
	Color         uint32                 `protobuf:"varint,5,opt,name=color,proto3" json:"color,omitempty"`
	MidHash       string                 `protobuf:"bytes,6,opt,name=mid_hash,json=midHash,proto3" json:"mid_hash,omitempty"`
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Ctime         int64                  `protobuf:"varint,8,opt,name=ctime,proto3" json:"ctime,omitempty"`
	Weight        int32                  `protobuf:"varint,9,opt,name=weight,proto3" json:"weight,omitempty"`
	Action        string                 `protobuf:"bytes,10,opt,name=action,proto3" json:"action,omitempty"`
	Pool          int32                  `protobuf:"varint,11,opt,name=pool,proto3" json:"pool,omitempty"`
	IdStr         string                 `protobuf:"bytes,12,opt,name=id_str,json=idStr,proto3" json:"id_str,omitempty"`
	Attr          int32                  `protobuf:"varint,13,opt,name=attr,proto3" json:"attr,omitempty"`
	Animation     string                 `protobuf:"bytes,14,opt,name=animation,proto3" json:"animation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DanmakuElem) Reset() {
	*x = DanmakuElem{}
	mi := &file_proto_danmaku_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DanmakuElem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanmakuElem) ProtoMessage() {}

func (x *DanmakuElem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_danmaku_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanmakuElem.ProtoReflect.Descriptor instead.
func (*DanmakuElem) Descriptor() ([]byte, []int) {
	return file_proto_danmaku_proto_rawDescGZIP(), []int{1}
}

func (x *DanmakuElem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DanmakuElem) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *DanmakuElem) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *DanmakuElem) GetFontsize() int32 {
	if x != nil {
		return x.Fontsize
	}
	return 0
}

func (x *DanmakuElem) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *DanmakuElem) GetMidHash() string {
	if x != nil {
		return x.MidHash
	}
	return ""
}

func (x *DanmakuElem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DanmakuElem) GetCtime() int64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

func (x *DanmakuElem) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *DanmakuElem) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *DanmakuElem) GetPool() int32 {
	if x != nil {
		return x.Pool
	}
	return 0
}

func (x *DanmakuElem) GetIdStr() string {
	if x != nil {
		return x.IdStr
	}
	return ""
}

func (x *DanmakuElem) GetAttr() int32 {
	if x != nil {
		return x.Attr
	}
	return 0
}

func (x *DanmakuElem) GetAnimation() string {
	if x != nil {
		return x.Animation
	}
	return ""
}

type DanmakuAIFlag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DmFlags       []*DanmakuFlag         `protobuf:"bytes,1,rep,name=dm_flags,json=dmFlags,proto3" json:"dm_flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DanmakuAIFlag) Reset() {
	*x = DanmakuAIFlag{}
	mi := &file_proto_danmaku_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DanmakuAIFlag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanmakuAIFlag) ProtoMessage() {}

func (x *DanmakuAIFlag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_danmaku_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanmakuAIFlag.ProtoReflect.Descriptor instead.
func (*DanmakuAIFlag) Descriptor() ([]byte, []int) {
	return file_proto_danmaku_proto_rawDescGZIP(), []int{2}
}

func (x *DanmakuAIFlag) GetDmFlags() []*DanmakuFlag {
	if x != nil {
		return x.DmFlags
	}
	return nil
}

type DanmakuFlag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dmid          int64                  `protobuf:"varint,1,opt,name=dmid,proto3" json:"dmid,omitempty"`
	Flag          uint32                 `protobuf:"varint,2,opt,name=flag,proto3" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DanmakuFlag) Reset() {
	*x = DanmakuFlag{}
	mi := &file_proto_danmaku_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DanmakuFlag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanmakuFlag) ProtoMessage() {}

func (x *DanmakuFlag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_danmaku_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanmakuFlag.ProtoReflect.Descriptor instead.
func (*DanmakuFlag) Descriptor() ([]byte, []int) {
	return file_proto_danmaku_proto_rawDescGZIP(), []int{3}
}

func (x *DanmakuFlag) GetDmid() int64 {
	if x != nil {
		return x.Dmid
	}
	return 0
}

func (x *DanmakuFlag) GetFlag() uint32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

var File_proto_danmaku_proto protoreflect.FileDescriptor

const file_proto_danmaku_proto_rawDesc = "" +
	"\n" +
	"\x13proto/danmaku.proto\x12 bilibili.community.service.dm.v1\"\xb7\x01\n" +
	"\x10DmSegMobileReply\x12C\n" +
	"\x05elems\x18\x01 \x03(\v2-.bilibili.community.service.dm.v1.DanmakuElemR\x05elems\x12\x14\n" +
	"\x05state\x18\x02 \x01(\x05R\x05state\x12H\n" +
	"\aai_flag\x18\x03 \x01(\v2/.bilibili.community.service.dm.v1.DanmakuAIFlagR\x06aiFlag\"\xd7\x02\n" +
	"\vDanmakuElem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x05R\bprogress\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\x05R\x04mode\x12\x1a\n" +
	"\bfontsize\x18\x04 \x01(\x05R\bfontsize\x12\x14\n" +
	"\x05color\x18\x05 \x01(\rR\x05color\x12\x19\n" +
	"\bmid_hash\x18\x06 \x01(\tR\amidHash\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x14\n" +
	"\x05ctime\x18\b \x01(\x03R\x05ctime\x12\x16\n" +
	"\x06weight\x18\t \x01(\x05R\x06weight\x12\x16\n" +
	"\x06action\x18\n" +
	" \x01(\tR\x06action\x12\x12\n" +
	"\x04pool\x18\v \x01(\x05R\x04pool\x12\x15\n" +
	"\x06id_str\x18\f \x01(\tR\x05idStr\x12\x12\n" +
	"\x04attr\x18\r \x01(\x05R\x04attr\x12\x1c\n" +
	"\tanimation\x18\x0e \x01(\tR\tanimation\"Y\n" +
	"\rDanmakuAIFlag\x12H\n" +
	"\bdm_flags\x18\x01 \x03(\v2-.bilibili.community.service.dm.v1.DanmakuFlagR\admFlags\"5\n" +
	"\vDanmakuFlag\x12\x12\n" +
	"\x04dmid\x18\x01 \x01(\x03R\x04dmid\x12\x12\n" +
	"\x04flag\x18\x02 \x01(\rR\x04flagB?Z=github.com/FortyTwoCn/cyber-amber/internal/bili/danmaku/pb;pbb\x06proto3"

var (
	file_proto_danmaku_proto_rawDescOnce sync.Once
	file_proto_danmaku_proto_rawDescData []byte
)

func file_proto_danmaku_proto_rawDescGZIP() []byte {
	file_proto_danmaku_proto_rawDescOnce.Do(func() {
		file_proto_danmaku_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_danmaku_proto_rawDesc), len(file_proto_danmaku_proto_rawDesc)))
	})
	return file_proto_danmaku_proto_rawDescData
}

var file_proto_danmaku_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_danmaku_proto_goTypes = []any{
	(*DmSegMobileReply)(nil), // 0: bilibili.community.service.dm.v1.DmSegMobileReply
	(*DanmakuElem)(nil),      // 1: bilibili.community.service.dm.v1.DanmakuElem
	(*DanmakuAIFlag)(nil),    // 2: bilibili.community.service.dm.v1.DanmakuAIFlag
	(*DanmakuFlag)(nil),      // 3: bilibili.community.service.dm.v1.DanmakuFlag
}
var file_proto_danmaku_proto_depIdxs = []int32{
	1, // 0: bilibili.community.service.dm.v1.DmSegMobileReply.elems:type_name -> bilibili.community.service.dm.v1.DanmakuElem
	2, // 1: bilibili.community.service.dm.v1.DmSegMobileReply.ai_flag:type_name -> bilibili.community.service.dm.v1.DanmakuAIFlag
	3, // 2: bilibili.community.service.dm.v1.DanmakuAIFlag.dm_flags:type_name -> bilibili.community.service.dm.v1.DanmakuFlag
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_danmaku_proto_init() }
func file_proto_danmaku_proto_init() {
	if File_proto_danmaku_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_danmaku_proto_rawDesc), len(file_proto_danmaku_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_danmaku_proto_goTypes,
		DependencyIndexes: file_proto_danmaku_proto_depIdxs,
		MessageInfos:      file_proto_danmaku_proto_msgTypes,
	}.Build()
	File_proto_danmaku_proto = out.File
	file_proto_danmaku_proto_goTypes = nil
	file_proto_danmaku_proto_depIdxs = nil
}
